version: '3.4'
services:
  app:
    build:
      context: ./src
    network_mode: host
    environment:
      - ENVIRONMENT=Development
      - NAMESPACE=kube-system
    volumes:
      - $HOME/.kube/config:/root/.kube/config:ro
