name: "Run dockerised CSharp app using k3d"
on: [push, workflow_dispatch]

env:
  cluster-name: "csharp-cluster"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  docker-compose-build:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v2
      - name: "Start k3d"
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: ${{ env.cluster-name }}
          args: >-
            --agents 1
            --config=.github/assets/k3d.yaml

      - name: Wait for cluster to finish bootstraping
        run: |
          kubectl config set-context ${{ env.cluster-name }} --namespace default
          kubectl cluster-info
          kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

      - name: Run and test demo
        run: |
          docker-compose up --build --force-recreat
