name: "Run dockerised CSharp app using KinD"
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  docker-compose-build:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v2
      - name: Start KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          wait: 300s
          config: kind.yaml

      - name: Wait for cluster to finish bootstraping
        run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

      - name: Run and test demo
        run: |
          docker-compose up --build --force-recreat
